# src/main/resources/logging.properties
# Configuración de logs

handlers=java.util.logging.ConsoleHandler
.level=INFO

java.util.logging.ConsoleHandler.level=INFO
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter

# Niveles por paquete
com.gestorempresarial.dao.level=FINE
com.gestorempresarial.controlador.level=INFO
com.gestorempresarial.vista.level=INFO